#!/usr/bin/env bash

## assumes a file cookiekey.txt in the same directory containing the session key.
## to find this, go to input page in browser, hit reload, view request's header for the 
## input file.


Y="2023" # year
D=$1    # day

while IFS= read -r line
do  
    curl "https://adventofcode.com/${Y}/day/${D}/input" -H "cookie: session=$line" -o "input.txt"

DIR="day${D}"
mv input.txt ${DIR}/
done < "cookiekey.txt"
