#!/usr/bin/env bash

Y="2023" # year
D=$1    # day
DIR="day${D}"
NAME="${DIR}.py"
if [ -d "${DIR}" ]; then
    printf "Directory already exists!"
    google-chrome https://adventofcode.com/${Y}/day/${D}
    exit
fi

mkdir -p ${DIR}
cd ${DIR}
cp ../template.py ${NAME}
cd ..
./getinput ${D}
code .
google-chrome https://adventofcode.com/${Y}/day/${D}



#dune init project ${DIR}
#cd ${DIR}
#dune build
#cp ../templates/Makefile .
#mkdir vendor
#cd vendor
#ln -s ../../aocutils aocutils
#cd ..